---
title: "Heatmap"
author: "Tu Hu"
format: html
editor: visual
---

## Load packages

```{r}
suppressMessages(
  {
  library(dplyr)
  library(SummarizedExperiment)
  library(tidySummarizedExperiment)
  library(tidybulk)
  library(ComplexHeatmap)    
  }
)
```

## Load data

```{r}
se <- readRDS("../data/se_pcoding_scale_abundant_filtS.rds")

# filter genes with no names
#se <- 
se <- se[rownames(se)[!rownames(se) %>% stringr::str_detect("ENSMFAG")], ]


```

```{r}
se_abundant_var100 <- 
  se %>% 
  keep_variable(top = 100) 

assay(se_abundant_var100, 4) <- 
  se_abundant_var100 %>% assay(3) %>% log1p()

assayNames(se_abundant_var100) <- 
  c(assayNames(se_abundant_var100)[1:3], "log2counts")

count <- 
  se_abundant_var100 %>% assay(4) %>% t() %>% scale() %>% t()

```

## Heatmap

```{r}
annotation <- 
  colData(se) %>% as_tibble() %>% 
  select(vacc, timepoint) %>% 
  mutate(
    vacc = case_when(
      timepoint == "pre" ~ "baseline",
      vacc == "H107_CAF04_CpG" ~ "CAF10b",
      vacc == "H107_CAF09c" ~ "CAF09hi"),
    vacc = factor(vacc),
    timepoint = ifelse(timepoint == "pre", "baseline", as.character(timepoint)),
    timepoint = factor(timepoint, levels = c("baseline", "immu1", "immu2"))
    )



timepoint_color <- c("black", "#B9B7B7", "#646161")
                     # , "#2F2F2F")
names(timepoint_color) <- levels(annotation$timepoint)

vaccine_color <- c("white", "red", "blue")
names(vaccine_color) <- c("baseline", "CAF10b", "CAF09hi")

heatmap_annotation <- 
  HeatmapAnnotation(
    timepoint = annotation$timepoint %>% factor,
    vaccine = annotation$vacc,
    col = list(timepoint = timepoint_color,
               vaccine = vaccine_color),
    na_col = "white",
    annotation_legend_param = list(
      vaccine = list(labels = c("CAF10b", "CAF09hi"),
                     at = c("CAF10b", "CAF09hi"),
                     title = "vaccine",
                     legend_gp = gpar(fill = c("red", "blue"))
                     )
    )
  )


heatmap <- 
  Heatmap(count,
          name = "gene expression",
          column_dend_reorder = TRUE,
          show_column_names = FALSE,
          top_annotation = heatmap_annotation,
          height = unit(22, "cm"),
          width = unit(8, "cm"), 
          row_names_gp = gpar(fontsize = 7))
```

```{r}
png("../data/figure/heatmap_unsupervised.png", height = 30, width = 16, units = "cm", res = 600)
draw(heatmap, 
     heatmap_legend_side = "left",
     annotation_legend_side = "left", 
     merge_legend = FALSE)
dev.off()
```

```{r}
heatmap_semisupervised <- 
  Heatmap(count,
          name = "gene expression",
          column_dend_reorder = TRUE,
          show_column_names = FALSE,
          top_annotation = heatmap_annotation,
          height = unit(22, "cm"),
          width = unit(8, "cm"), 
          row_names_gp = gpar(fontsize = 7), 
          column_split =  annotation$vacc)
png("../data/figure/heatmap_semisupervised.png", height = 30, width = 17, units = "cm", res = 600)
draw(heatmap_semisupervised, 
     heatmap_legend_side = "left",
     annotation_legend_side = "left", 
     merge_legend = FALSE)
dev.off()
```
