---
title: "RNA-seq: data cleaning"
author: "Tu Hu"
date: "2023-06-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load package
```{r}
library(dplyr)
library(stringr)
library(tidybulk)
library(tidySummarizedExperiment)
library(biomaRt)
library(ggplot2)
library(ggpubr)
```

## Load data
```{r data}
se <- readRDS("../data/salmon.merged.gene_counts.rds")
```

### meta data
```{r generate metadata}
metadata <-
  tibble(sample_name = colnames(se)) %>% 
  mutate(animal = sample_name %>% str_extract("[:alnum:]{1,6}"),
         sample_date =  sample_name %>% str_extract("[:digit:]{4}\\.[:digit:]{2}\\.[:digit:]{2}"),
         vacc = case_when(
           animal %in% c("CFL098", "CGB091", "CGB093", "CGB097", "CGB104") ~ "H107_CAF04_CpG",
           animal %in% c("CFL069", "CGA054", "CGB065", "CGB088", "CGC010") ~ "H107_CAF09c"
         ),
         timepoint = case_when(
           sample_date == "2019.06.24" ~ "pre", # pre-immunization
           sample_date == "2019.06.25" ~ "immu1", # day 1 after immunization 1
           sample_date == "2019.07.23" ~ "immu2" # day 1 after immunization 2
         ),
         timepoint = factor(timepoint, levels = c("pre", "immu1", "immu2")))
col_data <- 
  metadata %>% tibble::column_to_rownames("sample_name") %>% 
  DataFrame()
colData(se) <- col_data
```

### gene data
```{r clean rowdata}
ensembl <- useEnsembl(biomart = "genes", 
                      dataset = "mfascicularis_gene_ensembl", mirror = "useast")
gene_data <- getBM(attributes = c("ensembl_gene_id", "description", "gene_biotype"), 
                   mart = ensembl)
gene_data_Type <- 
  rowData(se) %>% as_tibble(rownames = "rowname") %>% 
  left_join(gene_data, by = c("gene_id" = "ensembl_gene_id"))

rowData(se) <- gene_data_Type %>% tibble::column_to_rownames() %>% DataFrame()

if (!file.exists("../data/gene_data_Type.rds")) {
  saveRDS(gene_data_Type, "../data/gene_data_Type.rds")
}

```

```{r generate se_pcoding}
se_pcoding <- se[rowData(se)$gene_biotype == "protein_coding", ] # protein coding gene
```


# PCA plot
```{r detect abundant and scale counts}
se_pcoding_scale_abundant <- 
  se_pcoding %>% 
  identify_abundant() %>% 
  scale_abundance()

rownames(se_pcoding_scale_abundant) <- 
  rowData(se_pcoding_scale_abundant)$gene_name
```

```{r pca}
pca <- se_pcoding_scale_abundant %>% reduce_dimensions(method = "PCA")

pca %>% pivot_sample() %>% 
  ggscatter(x = "PC1", y = "PC2", label = ".sample", )
```


```{r}
se_pcoding_scale_abundant_filtS <- 
  se_pcoding_scale_abundant[, !colnames(se) %in% c("CGB097.2019.06.24", "CGB065.2019.06.24")]

pca_filtS <- se_pcoding_scale_abundant_filtS %>% reduce_dimensions(method = "PCA")

pca_filtS %>% pivot_sample() %>% 
  ggscatter(x = "PC1", y = "PC2", label = ".sample")

pca_filtS %>% pivot_sample() %>% 
  mutate(timepoint_vacc = paste(timepoint, vacc)) %>% 
  ggscatter(x = "PC1", y = "PC2", 
            color = "timepoint", shape = "vacc",
            ellipse = T,
            mean.point = T)

saveRDS(se_pcoding_scale_abundant_filtS, "../data/se_pcoding_scale_abundant_filtS.rds")
```

