---
title: "The bioinformatics compendium"
---

## Motivation

This is a bioinformatics compendium for the publication: [Woodworth et al. A novel adjuvant formulation induces robust Th1/Th17 memory and mucosal recall responses in Non-Human Primates](https://pubmed.ncbi.nlm.nih.gov/).

The authors strive to contribute to the scientific rigor, reproducibility, and 
transparency. 

Thus, we provide this compendium, in order to:

- Document a fully reproducible pipeline

- Facilitate the readers to freely access the data, statistical models, analysis

## Data availability

- [GSExxxx](): RNA-seq data for 30 samples has been deposited on GEO under the accession number xxxx (pending approval)

## Bioinformatics methods and resources


### Refernce genome and annotation

* Ensembl genome assembilies: Macaca_fascicularis_6.0 (GCA_011100615.1), [fasta file](https://ftp.ensembl.org/pub/release-109/fasta/macaca_fascicularis/dna/Macaca_fascicularis.Macaca_fascicularis_6.0.dna_rm.toplevel.fa.gz)

* Ensembl annotation release: 109, [gtf file](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/012/559/485/GCF_012559485.2_MFA1912RKSv2/GCF_012559485.2_MFA1912RKSv2_genomic.gtf.gz)

### GitHub repository

#### Structure

| File                                       | Description                                                        |
| ------------------------------------------ | ------------------------------------------------------------------ |
| analysis\0_generate_nextflow_input.R       | generate input file for nextflow                                   |
| analysis\1_RNA_SEQ_MAPPING.sh              | RNA-seq maaping by nf-core (STAR/Salmon)                           |
| analysis\2_RNA_SEQ_MAPPING_SALMON.sh       | RNA-seq mapping by nf-core (only Salmon)                           |
| analysis\3_RNAseq_data_cleaning.Rmd        | RNA-seq: data cleaning and QC                                      |
| analysis\1_RNAseq_downstream_1.Rmd         | Figure 4a - PCA plots                                              |
| analysis\5_vacc_pre_pathway_enrichment.qmd | Figure 4b - Bubble plot for fGSEA pathway enrichment analysis      |
| analysis\6_correlation_late_response.qmd   | Figure 4c - correlate early blood signature with late response     |
| renv.lock                                  | The version of R/Bioconductor packages was documented using `renv` |
